### PR TITLE
Implement the new simplified/improved algorithm

### PR DESCRIPTION
**Pull request by aradalvand**
https://github.com/sqids/sqids-spec/issues/11

### CODE REVIEW

**Comment by aradalvand** [comment]
@4kimov I'm having difficulty understanding the "multibyte character" check added in [this commit](https://github.com/sqids/sqids-spec/commit/5f68e229a5d8c70475d8dee6620f7fb2044474f3).
Is it specific to the JavaScript implementation? Or do we have to add it here as well?

**Comment by aradalvand** [comment]
I added it in [ac8145d](https://github.com/sqids/sqids-dotnet/pull/20/commits/ac8145dbc8908b8d9f5a3f66f52abcef3c68379a), I'll appreciate it if you take a look.

**Comment by LeaFrock** [comment]
I see the changes in unit tests. I wonder whether v3 will output a different id for a pointed `int` number with v2, even though the alphabet and other configs are all the same?

**Comment by aradalvand** [comment]
Hi @LeaFrock, actually yes. v3 outputs different IDs than v2, this is a new modified algorithm that brings about quite a few improvements — you can learn more about those in https://github.com/sqids/sqids-spec/issues/11.

But we don't plan to introduce breaking changes in the algorithm anymore.

**Comment by LeaFrock** [comment]
Well, it sounds reasonable, though it indeed makes some troubles to me. We've already been using this library in our production.

> we don't plan to introduce any more breaking changes in the algorithm

Hope so. And I also hope Sqids releases a stable(rather than pre-release) version for production soon. Thanks for your reply!

**Comment by aradalvand** [comment]
> Well, it sounds reasonable, though it indeed makes some troubles to me. We've already been using this library in our production.

Understandable. Sorry for the inconvenience. I didn't actually know whether anyone was already using the library in production but I assumed that it's probably not that many people, since it has been only a few weeks since the library was published. Hopefully the transition goes smoothly for you.

**Comment by LeaFrock** [comment]
I imported `HashIds` in the last project, and it has been running well since 2021. Recently we create a new project and at the very first time I want to choose `HashIds` again. 

When I'm going to check if there's a new release on the website, I'm surprised that `HashIds` rebrands to `Sqids`. Therefore ... you know the rest of the story 🤣 .

**Pull request merged**
